from flask import Blueprint, request, jsonify
from datetime import datetime
from backend.routes.auth import require_auth
from backend.models.chat_message import ChatMessageCreate
from backend.models.assignment import Scenario
from backend.utils.db import get_supabase_admin
from backend.services.llm_service import chat_with_stakeholder
from backend.services.assignment_service import get_assignment_by_id
from pydantic import ValidationError

bp = Blueprint('chat', __name__)

@bp.route('/<assignment_id>/messages', methods=['GET'])
@require_auth('student')
def get_chat_messages(assignment_id):
    """Get chat messages for an assignment"""
    try:
        student_nim = request.user['user_id']
        supabase = get_supabase_admin()
        
        # Verify assignment belongs to student
        assignment = get_assignment_by_id(assignment_id)
        if assignment['student_nim'] != student_nim:
            return jsonify({'error': 'Unauthorized'}), 403
        
        # Get chat messages
        result = supabase.table('chat_messages').select('*').eq('assignment_id', assignment_id).order('timestamp').execute()
        
        return jsonify({
            'success': True,
            'messages': result.data
        }), 200
        
    except ValueError as e:
        return jsonify({'error': str(e)}), 404
    except Exception as e:
        return jsonify({'error': 'Internal server error'}), 500

@bp.route('/<assignment_id>/message', methods=['POST'])
@require_auth('student')
def send_chat_message(assignment_id):
    """Send a chat message and get AI response (Actor LLM with meta-prompt)"""
    try:
        student_nim = request.user['user_id']
        data = request.get_json()
        
        # Validate input
        message_data = ChatMessageCreate(**data)
        
        supabase = get_supabase_admin()
        
        # Verify assignment belongs to student
        assignment = get_assignment_by_id(assignment_id)
        if assignment['student_nim'] != student_nim:
            return jsonify({'error': 'Unauthorized'}), 403
        
        # Save student message
        student_msg = supabase.table('chat_messages').insert({
            'assignment_id': assignment_id,
            'sender': 'student',
            'content': message_data.content
        }).execute()
        
        # Get recent chat history
        history_result = supabase.table('chat_messages').select('sender, content').eq('assignment_id', assignment_id).order('timestamp').execute()
        
        chat_history = [
            {'sender': msg['sender'], 'content': msg['content']}
            for msg in history_result.data
        ]
        
        # Parse scenario from assignment
        scenario_data = assignment['scenario_json']
        scenario = Scenario(**scenario_data)
        
        # Generate AI response using Actor LLM
        # The Actor uses the persona_system_instruction generated by Architect
        # No need to pass dataset info - it's already in the system instruction
        ai_response = chat_with_stakeholder(
            scenario=scenario,
            chat_history=chat_history,
            new_message=message_data.content
        )
        
        # Save AI response
        ai_msg = supabase.table('chat_messages').insert({
            'assignment_id': assignment_id,
            'sender': 'ai',
            'content': ai_response
        }).execute()
        
        return jsonify({
            'success': True,
            'response': ai_response,
            'timestamp': ai_msg.data[0]['timestamp']
        }), 200
        
    except ValidationError as e:
        return jsonify({'error': 'Invalid input', 'details': e.errors()}), 400
    except ValueError as e:
        return jsonify({'error': str(e)}), 404
    except Exception as e:
        print(f"Error in send_chat_message: {e}")
        return jsonify({'error': 'Internal server error'}), 500
