from pydantic import BaseModel
from typing import Optional, Dict, Any
from datetime import datetime

class Scenario(BaseModel):
    """Scenario generated by Architect LLM (meta-prompt architecture)"""
    scenario_title: str
    difficulty_level: str  # "Beginner" | "Intermediate" | "Advanced"
    stakeholder_name: str
    stakeholder_role: str
    email_body: str
    key_objectives: list[str]
    persona_system_instruction: str  # The Actor's system prompt (generated by Architect)

class Assignment(BaseModel):
    """Assignment model"""
    id: Optional[str] = None
    student_nim: str
    dataset_id: str
    scenario_json: Dict[str, Any]
    created_at: Optional[datetime] = None
    
    class Config:
        from_attributes = True

class AssignmentResponse(BaseModel):
    """Model for assignment response with full details"""
    id: str
    student_nim: str
    dataset_id: str
    scenario: Scenario
    created_at: datetime
    
    class Config:
        from_attributes = True

class AssignmentWithDataset(BaseModel):
    """Assignment with dataset details"""
    id: str
    student_nim: str
    dataset: Dict[str, Any]
    scenario: Scenario
    created_at: datetime

class RegenerateAssignment(BaseModel):
    """Model for regenerating an assignment"""
    student_nim: str

